# Setup script for Android NDK toolchain (Windows PowerShell)
# This generates .cargo/config.toml with correct paths for your system

$ErrorActionPreference = "Stop"

# Change to script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location "$ScriptDir\.."

Write-Host "[INFO] Setting up Android NDK toolchain..." -ForegroundColor Green

# Check ANDROID_NDK_HOME
if (-not $env:ANDROID_NDK_HOME) {
    # Try common locations
    $commonPaths = @(
        "$env:LOCALAPPDATA\Android\Sdk\ndk",
        "$env:USERPROFILE\AppData\Local\Android\Sdk\ndk",
        "C:\Android\sdk\ndk"
    )
    
    foreach ($path in $commonPaths) {
        if (Test-Path $path) {
            $ndkVersions = Get-ChildItem $path -Directory | Sort-Object Name -Descending
            if ($ndkVersions.Count -gt 0) {
                $env:ANDROID_NDK_HOME = $ndkVersions[0].FullName
                Write-Host "[INFO] Auto-detected NDK: $env:ANDROID_NDK_HOME" -ForegroundColor Yellow
                break
            }
        }
    }
}

if (-not $env:ANDROID_NDK_HOME) {
    Write-Host "[ERROR] ANDROID_NDK_HOME is not set" -ForegroundColor Red
    Write-Host "[INFO] Please set it to your NDK path:" -ForegroundColor Cyan
    Write-Host '  $env:ANDROID_NDK_HOME = "C:\Users\<user>\AppData\Local\Android\Sdk\ndk\<version>"'
    exit 1
}

if (-not (Test-Path $env:ANDROID_NDK_HOME)) {
    Write-Host "[ERROR] ANDROID_NDK_HOME directory does not exist: $env:ANDROID_NDK_HOME" -ForegroundColor Red
    exit 1
}

$Toolchain = "$env:ANDROID_NDK_HOME\toolchains\llvm\prebuilt\windows-x86_64\bin"

if (-not (Test-Path $Toolchain)) {
    Write-Host "[ERROR] Toolchain not found: $Toolchain" -ForegroundColor Red
    exit 1
}

Write-Host "[INFO] Using NDK: $env:ANDROID_NDK_HOME" -ForegroundColor Green
Write-Host "[INFO] Toolchain: $Toolchain" -ForegroundColor Green

# Create .cargo directory
New-Item -ItemType Directory -Force -Path ".cargo" | Out-Null

# Escape backslashes for TOML
$ToolchainEscaped = $Toolchain -replace '\\', '\\\\'

# Generate config.toml
$configContent = @"
# Auto-generated by setup-android-toolchain.ps1
# Do not commit this file - it contains machine-specific paths

[target.aarch64-linux-android]
linker = "$ToolchainEscaped\\\\aarch64-linux-android21-clang.cmd"

[target.armv7-linux-androideabi]
linker = "$ToolchainEscaped\\\\armv7a-linux-androideabi21-clang.cmd"

[target.x86_64-linux-android]
linker = "$ToolchainEscaped\\\\x86_64-linux-android21-clang.cmd"

[target.i686-linux-android]
linker = "$ToolchainEscaped\\\\i686-linux-android21-clang.cmd"

[env]
CC_aarch64_linux_android = "$ToolchainEscaped\\\\aarch64-linux-android21-clang.cmd"
AR_aarch64_linux_android = "$ToolchainEscaped\\\\llvm-ar.exe"
CC_armv7_linux_androideabi = "$ToolchainEscaped\\\\armv7a-linux-androideabi21-clang.cmd"
AR_armv7_linux_androideabi = "$ToolchainEscaped\\\\llvm-ar.exe"
CC_x86_64_linux_android = "$ToolchainEscaped\\\\x86_64-linux-android21-clang.cmd"
AR_x86_64_linux_android = "$ToolchainEscaped\\\\llvm-ar.exe"
CC_i686_linux_android = "$ToolchainEscaped\\\\i686-linux-android21-clang.cmd"
AR_i686_linux_android = "$ToolchainEscaped\\\\llvm-ar.exe"
"@

$configContent | Out-File -FilePath ".cargo\config.toml" -Encoding UTF8

Write-Host "[INFO] Generated .cargo/config.toml" -ForegroundColor Green
Write-Host "[INFO] You can now run: cargo build --release --target <target> --features ffi,jni" -ForegroundColor Cyan
