#!/bin/bash
# Setup script for Android NDK toolchain (macOS/Linux)
# This generates .cargo/config.toml with correct paths for your system

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check ANDROID_NDK_HOME
if [ -z "$ANDROID_NDK_HOME" ]; then
    log_error "ANDROID_NDK_HOME is not set"
    log_info "Please set it to your NDK path:"
    log_info "  export ANDROID_NDK_HOME=~/Library/Android/sdk/ndk/<version>  # macOS"
    log_info "  export ANDROID_NDK_HOME=~/Android/Sdk/ndk/<version>          # Linux"
    exit 1
fi

if [ ! -d "$ANDROID_NDK_HOME" ]; then
    log_error "ANDROID_NDK_HOME directory does not exist: $ANDROID_NDK_HOME"
    exit 1
fi

# Detect host platform
case "$(uname -s)" in
    Darwin)
        NDK_HOST="darwin-x86_64"
        ;;
    Linux)
        NDK_HOST="linux-x86_64"
        ;;
    *)
        log_error "Unsupported OS: $(uname -s)"
        log_info "Use setup-android-toolchain.ps1 for Windows"
        exit 1
        ;;
esac

TOOLCHAIN="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/$NDK_HOST/bin"

if [ ! -d "$TOOLCHAIN" ]; then
    log_error "Toolchain not found: $TOOLCHAIN"
    exit 1
fi

log_info "Using NDK: $ANDROID_NDK_HOME"
log_info "Toolchain: $TOOLCHAIN"

# Create .cargo directory
mkdir -p .cargo

# Generate config.toml
cat > .cargo/config.toml << EOF
# Auto-generated by setup-android-toolchain.sh
# Do not commit this file - it contains machine-specific paths

[target.aarch64-linux-android]
linker = "$TOOLCHAIN/aarch64-linux-android21-clang"

[target.armv7-linux-androideabi]
linker = "$TOOLCHAIN/armv7a-linux-androideabi21-clang"

[target.x86_64-linux-android]
linker = "$TOOLCHAIN/x86_64-linux-android21-clang"

[target.i686-linux-android]
linker = "$TOOLCHAIN/i686-linux-android21-clang"

[env]
CC_aarch64_linux_android = "$TOOLCHAIN/aarch64-linux-android21-clang"
AR_aarch64_linux_android = "$TOOLCHAIN/llvm-ar"
CC_armv7_linux_androideabi = "$TOOLCHAIN/armv7a-linux-androideabi21-clang"
AR_armv7_linux_androideabi = "$TOOLCHAIN/llvm-ar"
CC_x86_64_linux_android = "$TOOLCHAIN/x86_64-linux-android21-clang"
AR_x86_64_linux_android = "$TOOLCHAIN/llvm-ar"
CC_i686_linux_android = "$TOOLCHAIN/i686-linux-android21-clang"
AR_i686_linux_android = "$TOOLCHAIN/llvm-ar"
EOF

log_info "Generated .cargo/config.toml"
log_info "You can now run: cargo build --release --target <target> --features ffi,jni"
